# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
        
    steps:
      - name: Support Long Path
        run: git config --system core.longpaths true
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          $ConfirmPreference = 'None'
          Invoke-WebRequest -Uri https://github.com/protocolbuffers/protobuf/releases/download/v2.5.0/protoc-2.5.0-win32.zip -OutFile protoc-2.5.0-win32.zip 
          Invoke-WebRequest -Uri https://github.com/protocolbuffers/protobuf/releases/download/v2.5.0/protobuf-2.5.0.zip -OutFile protobuf-2.5.0.zip
          Expand-Archive -LiteralPath protobuf-2.5.0.zip -DestinationPath ./
          Expand-Archive -LiteralPath protoc-2.5.0-win32.zip -DestinationPath ./protoc-2.5.0-win32
          move protoc-2.5.0-win32\protoc.exe protobuf-2.5.0\src
          Invoke-WebRequest -Uri http://www.zlib.net/zlib1212.zip -OutFile zlib1212.zip 
          Expand-Archive -LiteralPath zlib1212.zip -DestinationPath ./
          choco install cygwin
         
          
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build something requiring CL.EXE
        run: |
          $ConfirmPreference = 'None'
          Set-Alias -Name bash -Value C:\tools\cygwin\bin\bash.exe
          cd ./zlib-1.2.12
          nmake -f win32/Makefile.msc
          cd ..
          setx /M ZLIB_HOME "$pwd\zlib-1.2.12"
          setx /M Platform "x64"
          setx /M VCVARSPLAT "amd64"
          $Env:path=$Env:Path+";$pwd\protobuf-2.5.0\src"
          $Env:path=$Env:Path+";C:\tools\cygwin\bin"
          $Env:__VSCMD_PREINIT_PATH=$Env:__VSCMD_PREINIT_PATH+";C:\tools\cygwin\bin"

          protoc --version
          java -version
          bash -version
          Get-Command bash
          mvn package -Pdist -DskipTests -Dtar -e -X
          ls ./
