# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
        
    steps:
      - name: Support Long Path
        run: git config --system core.longpaths true
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          Invoke-WebRequest -Uri https://github.com/protocolbuffers/protobuf/releases/download/v21.5/protoc-21.5-win64.zip -OutFile protoc-21.5-win64.zip 
          Invoke-WebRequest -Uri https://github.com/protocolbuffers/protobuf/releases/download/v21.5/protobuf-all-21.5.zip  -OutFile protobuf-all-21.5.zip 
          Expand-Archive -LiteralPath protobuf-all-21.5.zip -DestinationPath ./
          Expand-Archive -LiteralPath protoc-21.5-win64.zip -DestinationPath ./protoc-21.5-win64
          move protoc-21.5-win64\bin\protoc.exe protobuf-21.5\src
          $Env:path=$Env:Path+";$pwd\protobuf-21.5\src"
          protoc --version
          Invoke-WebRequest -Uri http://www.zlib.net/zlib1212.zip -OutFile zlib1212.zip 
          Expand-Archive -LiteralPath zlib1212.zip -DestinationPath ./zlib1212
          
          
      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Build something requiring CL.EXE
        run: |
          cd ./zlib1212
          nmake -f win32/Makefile.msc
          cd ..
          setx /M ZLIB_HOME "$pwd\zlib1212"
          setx /M Platform "x64"
          cd winutils
          mvn package -Pdist -DskipTests -Dtar -Dmaven.javadoc.skip=true
